Update nickname.ts
jailbreakdiscord/bot pull request #11
Opened 2018-10-05 19:43 UTC by alexdominat

2018-10-06 18:34 UTC, nullpixel requested changes
Overall PR is fine, just address my comment. Also might want to run prettier for code style things.

2018-10-06 18:34 UTC, nullpixel commented on src/discord/commands/moderation/nickname.ts
> +            await member.setNickname(nickname ? nickname : message.author.username,'Executed by ' + `${message.author.username}(${message.author.id})`)
Please use \`{}\` string interop here

2018-10-06 18:46 UTC, alexdominat commented on src/discord/commands/moderation/nickname.ts
> +            await member.setNickname(nickname ? nickname : message.author.username,'Executed by ' + `${message.author.username}(${message.author.id})`)
uh what do u mean

2018-10-29 11:31 UTC, nullpixel approved these changes
This can be merged when merge conflicts are resolved!

2019-01-03 13:29 UTC, closed without merging